swagger: '2.0'
info:
  title: IPFS API
  description: The InterPlanetary File System HTTP API
  version: 1.0.0
  contact:
    name: API Support
    url: 'https://github.com/ipfs/api/issues'
    email: support@ipfs.io
  license:
    name: MIT
    url: 'https://github.com/ipfs/ipfs/blob/master/LICENSE'
host: '127.0.0.1:5001'
schemes:
  - http
basePath: /api/v0
produces:
  - application/json
paths: {}
definitions: {}
